
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      username: eddi
      password: eddi@123
      authentication-database: admin
      database: test-db
      port: 27017
      host: localhost

  profiles:
    active: elk

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE